Add exception for mandatory releases info
When trying stackalytics with minimum default_data.json, TypeError
happens if the file doesn't contain releases data like:

  File "[..]/processor/main.py", line 330, in main
    runtime_storage_inst)
  File "[..]/processor/record_processor.py", line 42, in __init__
    self.releases_dates = [r['end_date'] for r in self.releases]
  TypeError: 'NoneType' object is not iterable

So the releases data is mandatory, this patch adds an exception to
understand the problem easily.

Change-Id: Id0efae913c202a30476d73a3821711c5250fcfee